<?php
/*
 * This file is part of the codeliner/php-ddd-cargo-sample package.
 * (c) Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<div class="jumbotron">
    <h1><?php echo $this->translate('Add new Voyage') ?></h1>    
    <p><?php echo $this->translate('The capacity of a Voyage controls how many Cargos can be booked. The size amount of all booked Cargos must be less than or equal the capacity. Only the Overbooking-Policy can temporary increase the capacity.') ?></p>
</div>
<div class="row">
    <div class="col-md-12">
        <?php
        $form = $this->form;
        $form->prepare();

        $form->setAttribute('method', 'post');
        
        echo $this->form()->openTag($form);
        
        $number = $form->get('voyage_number');
        echo $this->ztbFormElement($number);
        
        $name = $form->get('name');
        echo $this->ztbFormElement($name);
        
        $capacity = $form->get('capacity');
        echo $this->ztbFormElement($capacity);
        
        echo '<p></p>';

        echo $this->ztbFormElement($form->get('send'));

        echo $this->form()->closeTag();
        ?>
    </div>
</div>