<?php
/*
 * This file is part of the codeliner/php-ddd-cargo-sample package.
 * (c) Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>

<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Voyage %s'), $this->voyage->getVoyageNumber()->toString()) ?></h1>
    <p>-&nbsp;<?php echo  $this->voyage->getName() ?>&nbsp;-</p>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <h2>Overview</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                Full Capacity: <?php echo $voyage->getCapacity() ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                Available Capacity: <?php echo $voyage->getFreeCapacity() ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <h2>Booked Cargos</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul>
                    <?php foreach($this->voyage->getBookedCargos() as $cargo): ?>
                    <li><a href="<?php echo $this->url('application/default/trackingid', array('controller' => 'cargo', 'action' => 'show', 'trackingid' => $cargo->trackingId()->toString())) ?>"><?php echo $cargo->trackingId() ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>