<?php
/*
 * This file is part of the codeliner/php-ddd-cargo-sample package.
 * (c) Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<div class="jumbotron">
    <h1><?php echo $this->translate('Cargo Overview') ?></h1>
    <p><?php echo $this->translate('Choose a Cargo from the list to view it\'s routing details.') ?></p>
</div>
<div class="row">
    <div class="col-md-12">
        <?php if (empty($this->trackingIds)): ?>
        <p class="alert-danger"><?php echo $this->translate('The list is empty. You have to add a cargo first!'); ?></p>
        <?php else: ?>
        <ul id="cargo-list">
            <?php foreach ($this->trackingIds as $trackingId): ?>
            <li><a href="<?php echo $this->url('application/default/trackingid', array('controller' => 'cargo', 'action' => 'show', 'trackingid' => $trackingId)) ?>"><?php echo $trackingId ?></a></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('application/default', array('controller' => 'cargo', 'action' => 'add')) ?>"><?php echo $this->translate('Add new Cargo') ?> &raquo;</a></p>
    </div>
</div>
