<?php
/*
 * This file is part of the codeliner/php-ddd-cargo-sample package.
 * (c) Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<div class="jumbotron">
    <h1><?php echo $this->translate('Assign Itinerary to Cargo') ?></h1>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Cargo from <?php echo $this->cargo['origin']  ?> (<?php echo $this->cargo['trackingId'] ?> )</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h3>Current route specification</h3>
    </div>
</div>
<div class="row">
    <div class="col-md-6 alert-info">
        <strong>From: </strong><?php echo $this->routeSpecification['origin'] ?>
    </div>
    <div class="col-md-6 alert-info">
        <strong>To: </strong><?php echo $this->routeSpecification['destination'] ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h3>Available routes</h3>
    </div>
</div>
<?php foreach ($this->itineraries as $index => $itinerary): ?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default itinerary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Route') . ' ' . ($index+1) ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach ($itinerary['legs'] as $leg): ?>
                    <div class="row">
                        <div class="col-md-6">
                            <strong>Load location: </strong><?php echo $leg['loadLocation'] ?>
                        </div>
                        <div class="col-md-6">
                            <strong>Load time: </strong><?php echo $leg['loadTime'] ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <strong>Unload location: </strong><?php echo $leg['unloadLocation'] ?>
                        </div>
                        <div class="col-md-6">
                            <strong>Unload time: </strong><?php echo $leg['unloadTime'] ?>
                        </div>
                    </div>
                <?php endforeach ?>
                <div class="row">
                    <div class="col-md-12">
                        <a id="assign-itinerary-link-<?php echo $index ?>" href="<?php echo $this->url('assign-itinerary', array('trackingid' => $this->cargo['trackingId'], 'index' => $index)) ?>" class="btn btn-success">Assign Cargo</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endforeach ?>
