<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>PHP Cargo Shipping Application</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/css/style.css">
        <script language="javascript" type="text/javascript" src="/js/jquery.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/jquery.addons.js"></script>
        <script language="javascript" type="text/javascript" src="/js/bootstrap.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/notify.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lodash.js"></script>
        <script language="javascript" type="text/javascript" src="/js/riot.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/prooph.riot.app.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">                    
                    <a class="navbar-brand" href="/">PHP Cargo Shipping System</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#booking">Booking App</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <main></main>
            <hr>
            <footer>
                <p>&copy; 2013<?php echo (date('Y') > 2013)? ' - ' . date('Y') : ''; ?> by Alexander Miertsch. All rights reserved.</p>
            </footer>
        </div> <!-- /container -->
        <script type="text/javascript">
            <?php echo $this->compileRiot() ?>

            var CargoUI = ProophRiot.App.create({
                config : {
                    url : {
                        forResource : function (resource) {
                            return '/api/' + resource.getName() + 's/' + resource.getId();
                        }
                    },
                    chapter: "ChapterFour"
                },
                Resource : function (id, name, data) {
                    var self = this;

                    self.getId = function () {return id};
                    self.getName = function () {return name};
                    self.getProp = function(prop) {
                        return data[prop]? data[prop] : null;
                    }
                    self.setProp = function(prop, val) {
                        data[prop] = val;
                    }

                    self.props = function () {
                        return data;
                    }
                }
            });

            $(function () {
                CargoUI.bootstrap("main").ready();
            });
        </script>
    </body>
</html>
