<?php
/*
 * This file is part of the codeliner/php-ddd-cargo-sample package.
 * (c) Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<div class="jumbotron">
    <h1><?php echo $this->translate('Add new Cargo') ?></h1>
    <p><?php echo $this->translate('In the ChapterTwo version of the Shipping System you can specify origin and destination of a Cargo. In a second step, the booking system suggest possible routes and you can assign the new Cargo to one of the routes.') ?></p>
</div>
<div class="row">
    <div class="col-md-12">
        <?php
        $form = $this->form;
        $form->prepare();

        $form->setAttribute('method', 'post');
        
        echo $this->form()->openTag($form);
        
        $origin = $form->get('origin');
        echo $this->ztbFormElement($origin);

        $destination = $form->get('destination');
        echo $this->ztbFormElement($destination);
        
        $trackingId = $form->get('trackingId');
        echo $this->ztbFormElement($trackingId);
        
        echo '<p></p>';

        echo $this->ztbFormElement($form->get('send'));

        echo $this->form()->closeTag();
        ?>
    </div>
</div>