<?php
/*
 * This file is part of the codeliner/php-ddd-cargo-sample package.
 * (c) Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/* @var $cargo \CargoBackend\API\Dto\CargoDto */
$cargo = $this->cargo;
?>
<div class="jumbotron">
    <h1><?php echo $this->translate('Cargo Overview') ?></h1>
    <p><?php echo $cargo->getTrackingId() ?></p>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Cargo from <?php echo $this->translate($cargo->getOrigin())  ?></h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h3>Current route specification</h3>
    </div>
</div>
<div class="row">
    <div class="col-md-6 alert-info">
        <strong>From: </strong><?php echo $this->translate($cargo->getRouteSpecification()->getOrigin()) ?>
    </div>
    <div class="col-md-6 alert-info">
        <strong>To: </strong><?php echo $this->translate($cargo->getRouteSpecification()->getDestination()) ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h3>Available routes</h3>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default itinerary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Route') ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach ($cargo->getItinerary()->getLegs() as $leg): ?>
                    <div class="row">
                        <div class="col-md-6">
                            <strong>Load location: </strong><?php echo $this->translate($leg->getLoadLocation()) ?>
                        </div>
                        <div class="col-md-6">
                            <strong>Load time: </strong><?php echo $leg->getLoadTime() ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <strong>Unload location: </strong><?php echo $this->translate($leg->getUnloadLocation()) ?>
                        </div>
                        <div class="col-md-6">
                            <strong>Unload time: </strong><?php echo $leg->getUnloadTime() ?>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</div>

