<?php
/*
 * This file is part of the codeliner/php-ddd-cargo-sample package.
 * (c) Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<div class="jumbotron">
    <h1><?php echo $this->translate('Cargo Booking') ?></h1>
</div>
<div class="row">
    <div class="col-md-12">
        <p class="alert-<?php echo ($this->success)? 'info' : 'danger' ?>"><?php echo $this->translate($this->msg) ?></p>
    </div>
</div>
