<div class="jumbotron">
    <h1><?php echo $this->translate('Welcome to the PHP DDD Cargo Sample') ?></h1>
    <p><?php echo $this->translate('Congratulations! You have successfully installed the Container Shipping System. You are currently running the Chaper One Version of the Application.') ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/codeliner/php-ddd-cargo-sample" target="_blank"><?php echo $this->translate('Fork PHP DDD Cargo Sample on GitHub') ?> &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Goal of the Sample Application') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The Cargo Shipping System is based on the example used in Eric Evans book Domain Driven Design: Tackling Complexity in the Heart of Software. It\'s a PHP Version of the Cargo Sample to show how DDD can be applied in a PHP Project. %sZend Framework 2%s is used as a basis for the application layer and %sdoctrine 2%s is used for the infrastructure layer.'), '<a href="http://framework.zend.com/" target="_blank">', '</a>', '<a href="http://www.doctrine-project.org/" target="_blank">', '</a>') ?></p>                
            </div>
        </div>
    </div>
</div>